[package]
name = "ssr"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc_ast = { workspace = true }
oxc_span = { workspace = true }
oxc_allocator = { workspace = true }
oxc_ast_visit = { workspace = true }
oxc_traverse = { workspace = true }
oxc_semantic = { workspace = true }
oxc_parser = { workspace = true }

common = { workspace = true }

phf = { workspace = true, features = ["macros"] }
indexmap = { workspace = true }
